# Generated by Django 4.0.3 on 2024-02-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('car_chosen', models.CharField(max_length=100)),
                ('car_color', models.CharField(max_length=50)),
                ('number_of_days', models.IntegerField()),
                ('pickup_date', models.DateField()),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('total_bill', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
