# Generated by Django 5.0.2 on 2024-02-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRentalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('license_number', models.CharField(max_length=20)),
                ('license_image', models.ImageField(upload_to='license_images/')),
                ('car_type', models.CharField(choices=[('compact', 'Compact'), ('sedan', 'Sedan'), ('suv', 'SUV')], max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
