# Generated by Django 5.0.2 on 2024-02-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_carrentalbooking_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRentalBooking1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('license_number', models.CharField(max_length=20)),
                ('front_license_image', models.ImageField(upload_to='license_images/')),
                ('back_license_image', models.ImageField(upload_to='license_images/')),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('due_off_date', models.DateField()),
                ('due_off_time', models.TimeField()),
            ],
        ),
    ]
