# Generated by Django 5.0.2 on 2024-02-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_carrentalbooking1_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('transmission_type', models.CharField(max_length=20)),
                ('seat_number', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_duration_hours', models.PositiveIntegerField()),
                ('availability', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('car_photo', models.ImageField(upload_to='car_photos/')),
            ],
        ),
    ]
