# Generated by Django 5.0.2 on 2024-02-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0006_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_photo', models.ImageField(upload_to='car_photos')),
                ('car_make', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('transmission_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20)),
                ('seat_number', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_duration', models.PositiveIntegerField()),
                ('availability', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], max_length=20)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('additional_features', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
