# Generated by Django 5.0.2 on 2024-02-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0007_car1_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRentalBooking2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('license_number', models.CharField(max_length=20)),
                ('front_license_image', models.ImageField(upload_to='license_images/')),
                ('back_license_image', models.ImageField(upload_to='license_images/')),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('due_off_date', models.DateField()),
                ('due_off_time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('driver_choice', models.CharField(choices=[('driver', 'Driver'), ('self', 'Self Driver')], default='self', max_length=10)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CarRentalBooking1',
        ),
    ]
