# Generated by Django 5.0.2 on 2024-02-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0008_carrentalbooking2_delete_carrentalbooking1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrentalbooking2',
            name='back_license_image',
            field=models.ImageField(null=True, upload_to='license_images/'),
        ),
        migrations.AlterField(
            model_name='carrentalbooking2',
            name='front_license_image',
            field=models.ImageField(null=True, upload_to='license_images/'),
        ),
        migrations.AlterField(
            model_name='carrentalbooking2',
            name='license_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
