# Generated by Django 5.0.2 on 2024-02-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0009_alter_carrentalbooking2_back_license_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrentalbooking2',
            name='car_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
