# Generated by Django 5.0.2 on 2024-02-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0010_carrentalbooking2_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrentalbooking2',
            name='back_license_image',
            field=models.ImageField(default=None, null=True, upload_to='license_images/'),
        ),
        migrations.AlterField(
            model_name='carrentalbooking2',
            name='front_license_image',
            field=models.ImageField(default=None, null=True, upload_to='license_images/'),
        ),
        migrations.AlterField(
            model_name='carrentalbooking2',
            name='license_number',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
