# Generated by Django 5.0.2 on 2024-03-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0012_alter_carrentalbooking2_license_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRentalBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('license_number', models.CharField(default=None, max_length=20, null=True)),
                ('front_license_image', models.ImageField(default=None, null=True, upload_to='license_images/')),
                ('back_license_image', models.ImageField(default=None, null=True, upload_to='license_images/')),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('driver_choice', models.CharField(choices=[('driver', 'Driver'), ('self_driver', 'Self Driver')], default='self_driver', max_length=11)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('car_id', models.PositiveIntegerField(blank=True, null=True)),
                ('rental_duration_days', models.PositiveIntegerField(default=0)),
                ('rental_duration_hours', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='CarRentalBooking2',
        ),
    ]
