# Generated by Django 5.0.2 on 2024-03-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0013_carrentalbookings_delete_carrentalbooking2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrentalbookings',
            name='pickup_time',
            field=models.CharField(max_length=8),
        ),
    ]
