# Generated by Django 5.0.2 on 2024-03-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0014_alter_carrentalbookings_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrentalbookings',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrentalbookings',
            name='return_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
