# Generated by Django 5.0.2 on 2024-03-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0015_carrentalbookings_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrentalbookings',
            name='employee_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
