# Generated by Django 5.0.2 on 2024-03-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0017_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrentalbookings',
            name='work_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
