# Generated by Django 5.0.2 on 2024-03-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0019_employee_joining_date_employee_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car1',
            old_name='price',
            new_name='day_price',
        ),
        migrations.RemoveField(
            model_name='car1',
            name='rental_duration',
        ),
        migrations.AddField(
            model_name='car1',
            name='car_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos'),
        ),
        migrations.AddField(
            model_name='car1',
            name='car_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos'),
        ),
        migrations.AddField(
            model_name='car1',
            name='hour_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
