# Generated by Django 5.0.2 on 2024-04-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0020_rename_price_car1_day_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.CharField(max_length=8)),
                ('return_date', models.DateField()),
                ('return_time', models.CharField(max_length=8)),
            ],
        ),
    ]
