# Generated by Django 5.0.2 on 2024-04-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0021_carreservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrentalbookings',
            name='rental_duration_days',
        ),
        migrations.RemoveField(
            model_name='carrentalbookings',
            name='rental_duration_hours',
        ),
        migrations.AddField(
            model_name='carreservation',
            name='duration_unit',
            field=models.CharField(choices=[('hour', 'Hour(s)'), ('day', 'Day(s)')], default='hour', max_length=4),
        ),
    ]
