# Generated by Django 5.0.2 on 2024-04-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0022_remove_carrentalbookings_rental_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreservation',
            name='rental_duration',
            field=models.IntegerField(default=0),
        ),
    ]
