# Generated by Django 5.0.2 on 2024-04-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0023_carreservation_rental_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrentalbookings',
            name='duration_unit',
            field=models.CharField(default='hours', max_length=20),
        ),
        migrations.AddField(
            model_name='carrentalbookings',
            name='rental_duration',
            field=models.IntegerField(default=0),
        ),
    ]
