# Generated by Django 5.0.2 on 2024-04-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0024_carrentalbookings_duration_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrentalbookings',
            name='rental_duration',
            field=models.IntegerField(),
        ),
    ]
