# Generated by Django 5.0.2 on 2024-04-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0025_alter_carrentalbookings_rental_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('car_photo', models.ImageField(upload_to='car_photos')),
                ('car_photo_2', models.ImageField(blank=True, null=True, upload_to='car_photos')),
                ('car_photo_3', models.ImageField(blank=True, null=True, upload_to='car_photos')),
                ('car_make', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('transmission_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20)),
                ('seat_number', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], max_length=20)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], max_length=20)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('additional_features', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('number_of_days', models.PositiveIntegerField(default=1)),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CarRentalBooking',
        ),
    ]
