# Generated by Django 5.0.2 on 2024-04-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0026_package_delete_carrentalbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('driver_choice', models.CharField(default='self_drive', max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('front_license_image', models.ImageField(upload_to='license_images/')),
                ('back_license_image', models.ImageField(upload_to='license_images/')),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('number_of_days', models.PositiveIntegerField()),
            ],
        ),
    ]
