# Generated by Django 5.0.2 on 2024-04-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0027_carpackagebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpackagebooking',
            name='package_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
