# Generated by Django 5.0.2 on 2024-04-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0029_lastpickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpackagebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accepted'), ('reject', 'Rejected')], default='pending', max_length=10),
        ),
    ]
